version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
