spring:
  profiles:
    active: local

---
spring:
  config:
    activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/match_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: { mysql id }
    password: { mysql pw }
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800